### ISSUE TITLE
commas in updates do not work

### ISSUE THREAD

**Issue by xh3b4sd** [venturemark/webclient#105]
@marcusellison when writing updates using commas the content gets cut off at the comma. This should be verified with all kinds of special characters so that people are able to write real sentences. 

![Kapture 2021-01-03 at 16 41 24](https://user-images.githubusercontent.com/552769/103482712-ab7d5f00-4de2-11eb-948c-dd3210ff6ccd.gif)

**Comment by marcusellison** [comment]
@xh3b4sd this is a server error. I can verify that the content is sent to server intact

**Comment by xh3b4sd** [comment]
Good call. I know why. Need to fix this server side. 🙈

**Comment by xh3b4sd** [comment]
Fixed in https://github.com/venturemark/apiserver/pull/65.
