### ISSUE TITLE
current datapoint should be highlighted somehow

### ISSUE THREAD

**Issue by xh3b4sd** [venturemark/webclient#117]
@marcusellison when I flip the card I constantly have to think and look for the datapoint of the card. The crosshair could maybe be visible by default or maybe there could be another highlighting mechanism to adhere the navigation. People should not wonder where they are when they flip the card. 

![Kapture 2021-01-06 at 23 00 37](https://user-images.githubusercontent.com/552769/103827683-d7664200-5079-11eb-8837-b304962440ef.gif)

**Comment by xh3b4sd** [comment]
Please provide reasons and information why issues get closed. We do not just close issues like that. Thank you.

**Comment by marcusellison** [comment]
This issue is from a past version of Venturemark client and is now outdated, irrelevant.
