### ISSUE TITLE
suggestions for design improvements

### ISSUE THREAD

**Issue by xh3b4sd** [venturemark/webclient#17]
@marcusellison as per our latest changes with https://github.com/venturemark/webclient/pull/16 there were two issues catching my eye. The first is that when I scroll down there is kind of a disconnect between background and page. Also the profile and settings buttons do not have padding between the and of the screen at the bottom and themselves. 

<img width="815" alt="Screenshot 2020-11-14 at 13 50 32" src="https://user-images.githubusercontent.com/552769/99147360-af152500-2680-11eb-841d-1cb6fb892fdb.png">

---

Another minor issue with the send button is that it should disappear when there is no focus on the action bar and there is no update content written anymore. Right now once you focus the action bar the send button appears as it should, though it does not disappear anymore in case there is nothing to send. 

<img width="709" alt="Screenshot 2020-11-14 at 13 51 21" src="https://user-images.githubusercontent.com/552769/99147362-b0dee880-2680-11eb-9e59-42640ae173d2.png">

**Comment by marcusellison** [comment]
Good that you pointed these out. I'll prioritize working on it next.

**Comment by xh3b4sd** [comment]
The second part of this issue is not addressed. The send button is still present when losing focus on the action bar as of https://github.com/venturemark/webclient/pull/27.

**Comment by marcusellison** [comment]
I expected a separate issue to be opened for the editor - or a comment on #27  rather than reopening this issue since it's a different component.

Maybe the correct thing here is to disassociate the background bug with the bug where editor content triggers state change?

**Comment by xh3b4sd** [comment]
The workflow with issues in Github is in general that issues get reopened if they got closed but in fact not fixed. What I should have done in the first place though is to create two separate issues. The other day I just dumped all findings in here. I will try to be more accurate next time. ❤️

**Comment by marcusellison** [comment]
I think it can make sense to group presentation only adjustments (css, html, plasmic) but behavior should be separate. In the future I'll clarify.
