### ISSUE TITLE
useless options shown when creating venture on signup

### ISSUE THREAD

**Issue by xh3b4sd** [venturemark/webclient#242]
It is not apparent to me why we would show these buttons. I was in the middle of creating a venture. Out of curiosity I clicked around and then ended up losing all my input I made so far. This is unpleasant for the user and unnecessary friction we impose upon the user on our part. 

<img width="208" alt="Screenshot 2021-04-17 at 13 10 14" src="https://user-images.githubusercontent.com/552769/115111022-89b57b80-9f7e-11eb-8fa8-326e4f82d0e9.png">

**Comment by marcusellison** [comment]
This issue was fixed in #262
