### ISSUE TITLE
creating update with too long content drops all input

### ISSUE THREAD

**Issue by xh3b4sd** [venturemark/webclient#271]
I create an update with content that is too long. Too long on the backend means 280 characters. 

<img width="620" alt="Screenshot 2021-04-20 at 21 12 22" src="https://user-images.githubusercontent.com/552769/115451227-36ad2400-a21d-11eb-9418-d629fee05396.png">

Creating the update drops all content. That should not happen. The user should keep their content and get an error message or anything. 

<img width="617" alt="Screenshot 2021-04-20 at 21 12 32" src="https://user-images.githubusercontent.com/552769/115451238-390f7e00-a21d-11eb-81a4-13942ed26b60.png">

The backend error is only shown in the developer console. 

<img width="443" alt="Screenshot 2021-04-20 at 21 12 38" src="https://user-images.githubusercontent.com/552769/115451236-3876e780-a21d-11eb-85b9-d71830341220.png">

**Comment by marcusellison** [comment]
closing - no error message yet but I've restricted description input to less than 280 characters in last commit.
