### ISSUE TITLE
New User's first venture isn't recognized upon creating

### ISSUE THREAD

**Issue by marcusellison** [venturemark/webclient#334]
**Recreate:**

1. Start from empty database
2. Create a user
3. Create first Venture

**Expected Behavior**
- after venture is created, venture is visible in sidebar and user can see the add/edit timeline view.

**Actual Behavior**
- The user continues to see the create new venture view after creating first venture. In order to see venture in sidebar, the user must create a new venture.

**Comment by marcusellison** [comment]
It seems like the sidebar ventures are only visible if there is more than 1

**Comment by tfussell** [comment]
This is resolved by #337.
