### ISSUE TITLE
Unable to accept invite from a Venture

### ISSUE THREAD

**Issue by marcusellison** [venturemark/webclient#335]
**Recreate:**

Start from empty database...

1. Create a user
2. Create first Venture
3. Create a timeline
4. Invite a user to that Venture
5. logout existing user
6. go to email and click on invite link that directs to signin page
7. signin
8. create account

**Expected Behavior**

After an account is created, the user should be directed to the "joinventure" page to accept the invite 
 - in the client we update the invitation status which updates the user's permission to the venture serverside.

**Comment by tfussell** [comment]
This is resolved with #339.
