### ISSUE TITLE
No error message when posted update is too long

### ISSUE THREAD

**Issue by marcusellison** [venturemark/webclient#336]
Right now the backend doesn't allow for posts beyond 280 characters.

Some feedback in the client would be helpful to let the user know this isn't possible. We normally enable error state using a different state in plasmic such as is done in in the InputText component in profile-form.

This would need to be enabled in InputTextArea.

**Comment by tfussell** [comment]
Mitigated in #337 and followed up by https://github.com/venturemark/webclient/issues/338
