### ISSUE TITLE
Invited users can edit the timeline they've been invited to

### ISSUE THREAD

**Issue by marcusellison** [venturemark/webclient#356]
**Existing Behavior**

When I invite a user to view a timeline, they should have read-permission by default.

However, it looks as if I can edit the timeline/venture, and add members:
![Venturemark](https://user-images.githubusercontent.com/1753324/120697222-4ea1d580-c462-11eb-9e03-04b941a0a7bc.jpg)

![Venturemark](https://user-images.githubusercontent.com/1753324/120697288-62e5d280-c462-11eb-8821-3089a740e15e.jpg)

**Expected Behavior**

If a user is invited to a timeline as a member, we would expect that they have a read-only view for members, venture, and timeline settings.

**Note.** @disresz may need to adjust some things on the Plasmic side to provide you with this state cleanly.

**Comment by marcusellison** [comment]
Hey @tfussell , 

It looks like this view can be fixed by using the isOwner variant on add/edit venture, add/edit timeline, and add/edit member components when the current user is not an owner.

and on the sidebar, Victor is now changing sidebaritem to have an "isOwner" variant that hides the icon-dropdown.

**Comment by disresz** [comment]
Changed the components to use "isOwner" variant.
