### ISSUE TITLE
Remove member from timeline / venture

### ISSUE THREAD

**Issue by marcusellison** [venturemark/webclient#362]
in the same way we can remove pending invitations, we should be able to remove members from a venture or timeline.
![Venturemark](https://user-images.githubusercontent.com/1753324/122807768-d3715980-d280-11eb-9d98-52680dd207b6.jpg)

If the user isOwner of the venture, than he should be able to see the isOwner variant of member items which shows the option to remove the member from the venture or timeline:

![shared_-_Plasmic](https://user-images.githubusercontent.com/1753324/122807899-00257100-d281-11eb-8a95-3f06c0f3661d.jpg)

Clicking on the "X" should remove the role that provides access to the timeline (if in add/edit timeline members) or the venture (if in add/edit venture members)

**Comment by tfussell** [comment]
This is done now.
