### ISSUE TITLE
Timeline with same name in different venture gets selected 

### ISSUE THREAD

**Issue by disresz** [venturemark/webclient#466]
https://user-images.githubusercontent.com/13752908/145929457-704b3e73-4f7a-4461-93cd-68e0917db2ef.mov

**Comment by peterphan1996** [comment]
This one looks similar to https://github.com/venturemark/webclient/issues/462

**Comment by marcusellison** [comment]
Yup - I think this is a duplicate.

**Comment by tfussell** [comment]
This should be resolved after the recent PRs have been merged. We'll confirm soon.

**Comment by tfussell** [comment]
Appears to be fixed on Beta now.
