### ISSUE TITLE
Pressing spacebar in editor skips a character position

### ISSUE THREAD

**Issue by marcusellison** [venturemark/webclient#478]
**Existing Behavior:**
1. Copy and paste some text
2. try to edit the middle of a sentence with spaces and text

**Bug:**

3. When entering a space the cursor skips a character position, resulting in unexpected cursor position.

![](http://g.recordit.co/XmLR3fxf6S.gif)

**Comment by peterphan1996** [comment]
@marcusellison hey Marcus, I created this issue already https://github.com/venturemark/webclient/issues/470#issue-1082892421, and have that fixed in this PR https://github.com/venturemark/webclient/pull/474
